name: bounded

num_target_views: 3
num_context_views: 2

min_distance_between_context_views: 4
max_distance_between_context_views: 4
min_distance_to_context_views: 0

warm_up_steps: 0
initial_min_distance_between_context_views: 4
initial_max_distance_between_context_views: 4